import { useEffect } from 'react'
import { getSession } from "next-auth/react"
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Nav from '../components/general/Nav'
export default function Home({session}) {

  return (
    
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Nav/>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to E-wallet
        </h1>
        </main>
    </div>
  )
}


export const getServerSideProps = async (ctx)=> {
  const session = await getSession(ctx )

  console.log(session)
  if (session) {
    return{
      props:{
        session
      }
    }
  } else {
    return{
      redirect:{
        destination:'/api/auth/signin'
      },
      props:{}
    }
  }
  
}