import { useEffect } from 'react'
import { getSession, useSession } from "next-auth/react"
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Error from '../components/general/customModals/Error'
import ClientLayout from '../components/layout/Client'
export default function Home({session}) {


  return (
    <ClientLayout>
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Error/>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to E-wallet
        </h1>
        </main>
    </div>
    </ClientLayout>
  )
}


export const getServerSideProps = async (ctx)=> {
  const session = await getSession(ctx )

  if (session) {
    return{
      props:{
        session
      }
    }
  } else {
    return{
      redirect:{
        destination:'/api/auth/signin'
      },
      props:{}
    }
  }
  
}